
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: github-webhook
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.properator.io
  resources:
  - refreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
