---
apiVersion: v1
kind: Service
metadata:
  name: github-webhook
  namespace: system
  labels:
    control-plane: github-webhook
spec:
  ports:
    - port: 443
      name: http
      targetPort: http
  selector:
    control-plane: github-webhook
