apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github-webhook.yaml
- github-webhook-svc.yaml
images:
- name: github-webhook
  newName: michaelbeaumont/properator-github-webhook
  newTag: latest
secretGenerator:
- envs:
  - .env
  files:
  - id_rsa
  name: github-secrets
  type: Opaque
