apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github-webhook.yaml
- github-webhook-svc.yaml
images:
- name: github-webook
  newName: github-webhook
  newTag: latest
secretGenerator:
- envs:
  - .env
  name: github-secrets
  type: Opaque
